id = "ava-cli"
name = "AVA Cli"
description = "CypherpunkSamurai's open-source coding assistant"
version = "1.2.2"
schema_version = 1
authors = ["CypherpunkSamurai"]
repository = "https://github.com/CypherpunkSamurai/ava-cli"

[agent_servers.ava-cli]
name = "AVA Cli"
icon = "./icons/ava_cli.svg"

[agent_servers.ava-cli.targets.darwin-aarch64]
archive = "https://github.com/CypherpunkSamurai/ava-cli/releases/download/v1.2.2/ava-acp-darwin-aarch64-1.2.2.zip"
cmd = "./ava-acp"

[agent_servers.ava-cli.targets.darwin-x86_64]
archive = "https://github.com/CypherpunkSamurai/ava-cli/releases/download/v1.2.2/ava-acp-darwin-x86_64-1.2.2.zip"
cmd = "./ava-acp"

[agent_servers.ava-cli.targets.linux-aarch64]
archive = "https://github.com/CypherpunkSamurai/ava-cli/releases/download/v1.2.2/ava-acp-linux-aarch64-1.2.2.zip"
cmd = "./ava-acp"

[agent_servers.ava-cli.targets.linux-x86_64]
archive = "https://github.com/CypherpunkSamurai/ava-cli/releases/download/v1.2.2/ava-acp-linux-x86_64-1.2.2.zip"
cmd = "./ava-acp"

[agent_servers.ava-cli.targets.windows-aarch64]
archive = "https://github.com/CypherpunkSamurai/ava-cli/releases/download/v1.2.2/ava-acp-windows-aarch64-1.2.2.zip"
cmd = "./ava-acp.exe"

[agent_servers.ava-cli.targets.windows-x86_64]
archive = "https://github.com/CypherpunkSamurai/ava-cli/releases/download/v1.2.2/ava-acp-windows-x86_64-1.2.2.zip"
cmd = "./ava-acp.exe"
